//@flow

/*******************************************************************************
 * Public API
 *******************************************************************************/

export default [
  "Akkadian",
  "Bainvegni",
  "Batak",
  "Be kher hati",
  "Benvignût",
  "Benvnuwe",
  "Bi xêr bî",
  "Bienbenidu",
  "Bienllegau",
  "Bienvenida",
  "Bienvenius",
  "Boolkhent",
  "Buen binidu",
  "Bula",
  "Bures boahtin",
  "B’a’ntulena",
  "Ceud mìle fàilte",
  "Cimbrian",
  "Eguahé porá",
  "Emedi",
  "Ennidos",
  "Guarani",
  "Horas",
  "Kale ah maruhabaa",
  "Kíimak 'oolal",
  "Mabuhay",
  "Malipayong pag-abot",
  "Maliu mai",
  "Mauri",
  "Mauya",
  "Mayad-ayad nga pad-abot",
  "Mazanderani",
  "Merhbe",
  "Merħba",
  "Mi'kmaq",
  "Mir se vjên",
  "Miro peicak",
  "Mu amuhezwi",
  "Murakaza neza",
  "Märr-ŋamathirri",
  "N bèlantre",
  "Naragsak nga Idadanon",
  "Nau mai",
  "nuqneH",
  "Qaimarutin",
  "Romani",
  "Räxim itegez",
  "Salamat datang",
  "Salve",
  "Siya namkela nonke",
  "Soo dhowow",
  "T'aves baxtalo",
  "Talitali fiefia",
  "Tere tulõmast",
  "Tikilluaritsi",
  "tonk'peh",
  "Vælkomin",
  "Walcome",
  "Walloon",
  "Welkam",
  "Weltasualuleg",
  "Wilkomme",
  "Wilkóm",
  "Willkommen",
  "Witajće k nam",
  "Witakśo k nam",
  "Wolkom",
  "Wäljkiimen",
  "Ximopanōltih",
  "Xoş gəlmişsiniz",
  "Zoo siab txais tos",
  "fi'i",
  "nno; dalụ",
  "ǁKhoreǁhare.",
  "लसकुस",
  "ཕེབས་པར་དགའ་བསུ་ཞུ།",
  "Ẹ ku abọ",
];
