// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var Particle = /* module */[];

var Background = /* module */[];

function make(state) {
  if (state >= 106380200) {
    return /* record */[/* color : Error */106380200];
  } else {
    return /* record */[/* color : Black */-937474657];
  }
}

var Border = /* module */[/* make */make];

function view(param) {
  return /* record */[
          /* size */param[/* size */0],
          /* weight */param[/* weight */1],
          /* family */param[/* family */2],
          /* color */param[/* color */3]
        ];
}

function make$1(style) {
  if (typeof style === "number") {
    switch (style) {
      case 0 : 
          return /* record */[
                  /* size : Detail */615765681,
                  /* weight : Regular */-807830980,
                  /* family : Sans */925282419,
                  /* color : Black */-937474657
                ];
      case 1 : 
          return /* record */[
                  /* size : Body */737453762,
                  /* weight : Regular */-807830980,
                  /* family : Sans */925282419,
                  /* color : Black */-937474657
                ];
      case 2 : 
          return /* record */[
                  /* size : Code */748543309,
                  /* weight : Regular */-807830980,
                  /* family : Mono */859441219,
                  /* color : White */-588596599
                ];
      case 3 : 
          return /* record */[
                  /* size : Body */737453762,
                  /* weight : Bold */737455525,
                  /* family : Sans */925282419,
                  /* color : Black */-937474657
                ];
      
    }
  } else {
    return /* record */[
            /* size : Main */858743897,
            /* weight : Regular */-807830980,
            /* family : Mono */859441219,
            /* color */style[0]
          ];
  }
}

var Text = /* module */[
  /* make */make$1,
  /* view */view
];

function make$2(size) {
  return size;
}

var Spacer = /* module */[/* make */make$2];

var Atom = /* module */[
  /* Background */Background,
  /* Border */Border,
  /* Text */Text,
  /* Spacer */Spacer
];

exports.Particle = Particle;
exports.Atom = Atom;
/* No side effect */
