// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Row$ReactTemplate = require("./Row.bs.js");
var Block$ReactTemplate = require("./Block.bs.js");
var Column$ReactTemplate = require("./Column.bs.js");
var NavBar$ReactTemplate = require("./NavBar.bs.js");
var Spacer$ReactTemplate = require("./Spacer.bs.js");
var Content$ReactTemplate = require("./Content.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Row$ReactTemplate.make(/* Left_to_right */1066667312, /* Center */980392437, /* array */[ReasonReact.element(undefined, undefined, Block$ReactTemplate.make(undefined, "700px", /* array */[ReasonReact.element(undefined, undefined, Column$ReactTemplate.make(/* Top_down */164851116, /* array */[
                                  ReasonReact.element(undefined, undefined, NavBar$ReactTemplate.make(/* Default */-384499551, undefined, /* array */[])),
                                  ReasonReact.element(undefined, undefined, Spacer$ReactTemplate.make(/* XL */19700, /* array */[])),
                                  ReasonReact.element(undefined, undefined, Spacer$ReactTemplate.make(/* XL */19700, /* array */[])),
                                  ReasonReact.element(undefined, undefined, Content$ReactTemplate.make(/* :: */[
                                            "How do I use this thing?",
                                            /* :: */[
                                              "See the input box by the logo? Just type in a command and see the magic happen!",
                                              /* :: */[
                                                "Try osx/say, linux/du, or simply man.",
                                                /* :: */[
                                                  "Some commands are widely available with the same interface, some other have variants per operating system. Currently the tldr-pages project splits commands into 4 categories: common, linux, osx, and sunos.",
                                                  /* :: */[
                                                    "du, for example, is available under both linux and osx.",
                                                    /* [] */0
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ], /* array */[]))
                                ]))]))])), "text");

/*  Not a pure module */
