// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Row$ReactTemplate = require("./Row.bs.js");
var Text$ReactTemplate = require("./Text.bs.js");
var Block$ReactTemplate = require("./Block.bs.js");
var Fixed$ReactTemplate = require("./Fixed.bs.js");
var Input$ReactTemplate = require("./Input.bs.js");
var Border$ReactTemplate = require("./Border.bs.js");
var Column$ReactTemplate = require("./Column.bs.js");
var Spacer$ReactTemplate = require("./Spacer.bs.js");

var component = ReasonReact.statelessComponent("SearchInput");

function make(feedbackState, placeholder, value, children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return ReasonReact.element(undefined, undefined, Block$ReactTemplate.make("70px", "100%", /* array */[
                              ReasonReact.element(undefined, undefined, Border$ReactTemplate.make(feedbackState, /* array */[])),
                              value !== undefined ? React.createElement("div", undefined) : ReasonReact.element(undefined, undefined, Fixed$ReactTemplate.make(/* array */[ReasonReact.element(undefined, undefined, Column$ReactTemplate.make(/* Top_down */164851116, /* array */[
                                                    ReasonReact.element(undefined, undefined, Spacer$ReactTemplate.make(/* S */83, /* array */[])),
                                                    ReasonReact.element(undefined, undefined, Row$ReactTemplate.make(/* Left_to_right */1066667312, undefined, /* array */[
                                                              ReasonReact.element(undefined, undefined, Spacer$ReactTemplate.make(/* S */83, /* array */[])),
                                                              ReasonReact.element(undefined, undefined, Text$ReactTemplate.make(/* Main */[/* Gray */793050115], /* array */[placeholder]))
                                                            ]))
                                                  ]))])),
                              ReasonReact.element(undefined, undefined, Fixed$ReactTemplate.make(/* array */[ReasonReact.element(undefined, undefined, Column$ReactTemplate.make(/* Top_down */164851116, /* array */[
                                                  ReasonReact.element(undefined, undefined, Spacer$ReactTemplate.make(/* S */83, /* array */[])),
                                                  ReasonReact.element(undefined, undefined, Row$ReactTemplate.make(/* Left_to_right */1066667312, undefined, /* array */[
                                                            ReasonReact.element(undefined, undefined, Spacer$ReactTemplate.make(/* S */83, /* array */[])),
                                                            ReasonReact.element(undefined, undefined, Input$ReactTemplate.make(feedbackState >= 106380200 ? /* Main */[/* Error */106380200] : /* Main */[/* Black */-937474657], value !== undefined ? value : "", (function (param) {
                                                                        return /* () */0;
                                                                      }), /* array */[]))
                                                          ]))
                                                ]))]))
                            ]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
