// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Text$ReactTemplate = require("./Text.bs.js");
var Block$ReactTemplate = require("./Block.bs.js");
var Column$ReactTemplate = require("./Column.bs.js");
var Spacer$ReactTemplate = require("./Spacer.bs.js");

var component = ReasonReact.statelessComponent("Title");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return ReasonReact.element(undefined, undefined, Block$ReactTemplate.make("70px", "120px", /* array */[ReasonReact.element(undefined, undefined, Column$ReactTemplate.make(/* Top_down */164851116, /* array */[
                                        ReasonReact.element(undefined, undefined, Spacer$ReactTemplate.make(/* S */83, /* array */[])),
                                        ReasonReact.element(undefined, undefined, Text$ReactTemplate.make(/* Main */[/* Black */-937474657], /* array */["tldr"]))
                                      ]))]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var Style = 0;

exports.Style = Style;
exports.component = component;
exports.make = make;
/* component Not a pure module */
